# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-SimpleScan
version:      0.26
version_from: lib/App/SimpleScan.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    Regexp::Common:                0
    Scalar::Util:                  0
    Test::Differences:             0
    Test::More:                    0
    Test::WWW::Simple:             0.18
    Text::Balanced:                1.95
    WWW::Mechanize:                1.16
    WWW::Mechanize::Pluggable:     0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
